// Generated by CoffeeScript 1.6.3
var DashboardManager;

DashboardManager = new Marionette.Application();

DashboardManager.addRegions({
  mainRegion: "#content",
  sidebar: "#sidebar"
});

Marionette.Region.prototype.open = function(view) {
  this.$el.hide();
  this.$el.html(view.el);
  return this.$el.fadeIn(600);
};

DashboardManager.on("initialize:after", function() {
  DashboardManager.DashboardApp.Sidebar.Controller.listLinks();
  if (Backbone.history) {
    return Backbone.history.start();
  }
});
