// Generated by CoffeeScript 1.6.3
require.config({
  paths: {
    jquery: "libs/jquery",
    underscore: "libs/underscore",
    backbone: "libs/backbone",
    text: "libs/text",
    cs: "libs/cs",
    bootstrap: "libs/bootstrap",
    dropdown: "libs/bootstrap-dropdown",
    collapse: "libs/bootstrap-collapse",
    tab: "libs/bootstrap-tab",
    nod: "libs/nod",
    bacon: "libs/Bacon",
    marionette: 'libs/backbone.marionette'
  },
  shim: {
    bootstrap: ["jquery"],
    dropdown: ["bootstrap"],
    collapse: ["bootstrap"],
    tab: ["bootstrap"],
    nod: ["jquery"],
    backbone: {
      deps: ["underscore", "jquery"],
      exports: "Backbone"
    },
    underscore: {
      exports: "_"
    },
    marionette: {
      deps: ['jquery', 'underscore', 'backbone'],
      exports: 'Marionette'
    }
  }
});

require(["jquery", "app", "bootstrap", "marionette", "dropdown", "collapse", "tab", "nod", "bacon"], function($, App, Bootstrap, Marionette, dropdown, tab) {
  return App.initialize();
});
