// Generated by CoffeeScript 1.6.3
var API, MyRouter, myrouter;

DashboardManager.module('DashboardApp.Sidebar', function(Sidebar, DashboardManager, Backbone, Marionette, $, _) {
  return Sidebar.Controller = {
    listLinks: function() {
      var links, sidebarView;
      links = DashboardManager.request("link:entities");
      sidebarView = new Sidebar.Links({
        collection: links
      });
      return DashboardManager.sidebar.show(sidebarView);
    }
  };
});

DashboardManager.module('DashboardApp', function(DashboardApp, DashboardManager, Backbone, Marionette, $, _) {
  var API;
  DashboardApp.Router = Backbone.Marionette.AppRouter.extend({
    appRoutes: {
      "overview": "listContacts",
      "": "listContacts"
    }
  });
  API = {
    listContacts: function() {
      return console.log('wow');
    }
  };
  return DashboardManager.addInitializer(function() {
    return new DashboardApp.Router({
      controller: API
    });
  });
});

MyRouter = Backbone.Marionette.AppRouter.extend({
  appRoutes: {
    "dashboard#overview": "someMethod"
  },
  routes: {
    "aws-info": "someOtherMethod"
  },
  someOtherMethod: function() {
    return console.log('boom');
  },
  someMethod: function() {
    return console.log('boom');
  }
});

API = {
  someOtherMethod: function() {
    return console.log('boom');
  },
  someMethod: function() {
    return console.log('boom');
  },
  listContacts: function() {
    return console.log('wow');
  }
};

myrouter = new MyRouter({
  controller: API
});
