// Generated by CoffeeScript 1.6.3
DashboardManager.module('DashboardApp.Sidebar', function(Sidebar, DashboardManager, Backbone, Marionette, $, _) {
  Sidebar.Link = Marionette.ItemView.extend({
    className: "sidebar-link",
    tagName: 'li',
    template: "#sidebar-item",
    events: {
      'click': "highlightLink",
      'click a': "test"
    },
    loadContent: function() {
      return e.preventDefault();
    },
    highlightLink: function(e) {
      $('li').removeClass('selected');
      return this.$el.addClass('selected');
    }
  });
  return Sidebar.Links = Marionette.CompositeView.extend({
    template: '#sidebar-list-collection',
    itemView: Sidebar.Link,
    itemViewContainer: "ul"
  });
});
